---
language: python
services: docker
env:
  global:
    - namespace="j-vanwijk"
    - role_name="ansible_role_chrony"
  matrix:
    - image="ansible-molecule-centos" tag="7" cmd="/usr/sbin/init"
    - image="ansible-molecule-centos" tag="8" cmd="/usr/sbin/init"
    - image="ansible-molecule-centos" tag="latest" cmd="/usr/sbin/init"
cache: pip
install:
  - pip install --upgrade pip setuptools
  - pip install molecule docker
script:
  - python --version
  - ansible --version
  - molecule --version
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

...
